yoz_auth/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  get 'home/index'

  get 'home/show'

  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end

  devise_scope :user do
    root "devise/sessions#new"
  end

end

yoz_auth/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks

	validates :title, 
	presence: {message: "入力して下さい"},
	length: {minimum: 3, message: "文字列の長さが短すぎです"}
end

yoz_auth/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true
end

yoz_auth/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]
  def self.from_omniauth(auth)
  	User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.username = auth.info.nickname
  		user.email = auth.info.email
  	end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

end

yoz_auth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      projects_path
  end

  def after_sign_out_path_for resource
      new_user_session_path
  end 

  protected

    def configure_permitted_parameters
      # sign_inのときに、usernameも許可する
      devise_parameter_sanitizer.for(:sign_in) << :username
      # sign_upのときに、usernameも許可する
      devise_parameter_sanitizer.for(:sign_up) << :username
      #  account_updateのときに、usernameも許可する
      devise_parameter_sanitizer.for(:account_update) << :username

      # sign_inのときに、usernameも許可する
      devise_parameter_sanitizer.for(:sign_in) << :email
      # sign_upのときに、usernameも許可する
      devise_parameter_sanitizer.for(:sign_up) << :email
      #  account_updateのときに、usernameも許可する
      devise_parameter_sanitizer.for(:account_update) << :email
    end
end

yoz_auth/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
  end

  def show
  end
end

yoz_auth/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController 
	def twitter
		user = User.from_omniauth(request.env["omniauth.auth"])

		if user.persisted?
			flash[:notice] = "ログインできた"
			#Twitter.configure do |config|
     		#config.consumer_key = 'cxD22sxkxLBWINIPUPfg8ugpv'
     		#config.consumer_secret = 'wPf4gm71hhexHbeZlAnzSqvcIMq6uknrxN6fDlZpdI4d8AFDcX'
     		#config.oauth_token = '2418762361-BgqwcNIBYZkxjvVSRWmzE8PNil6YWov9TdL8sWV'
     		#config.oauth_token_secret = 'C03FxA3TablGhMLsFK6wMjAkg0bhiYbIEnFpm9WPbGLut'
        	#end

        	#@timeline = Twitter.home_timeline
			sign_in_and_redirect(user)
		else
			session["devise.user_attributes"] = user.attributes #モデルの全てのカラムと属性を取得する
      		redirect_to new_user_registration_url #_pathと書いても一緒だと思

		end

	end
end

yoz_auth/app/controllers/projects_controller.rb
require 'open-uri'

class ProjectsController < ApplicationController

	before_action :set_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

		@@client = Twitter::REST::Client.new do |config|
    	config.consumer_key = "cxD22sxkxLBWINIPUPfg8ugpv"
    	config.consumer_secret = "wPf4gm71hhexHbeZlAnzSqvcIMq6uknrxN6fDlZpdI4d8AFDcX"
    	config.access_token = "2418762361-BgqwcNIBYZkxjvVSRWmzE8PNil6YWov9TdL8sWV"
    	config.access_token_secret = "C03FxA3TablGhMLsFK6wMjAkg0bhiYbIEnFpm9WPbGLut"
		end

	def index
		@projects = Project.all
		#@ary = []
		#open("https://api.github.com/user?access_token=ab88e6c455bf74b94bbc47361e93d139cae76118") {|f|
  		#f.each_line {|line| @ary << line}
		#}
		@twitters = @@client.user_timeline("youichi0313")
	end

	def show
		#@project = Project.find(params[:id])
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to projects_path
		else
			render 'new' #newアクションということか
		end

	end

	def edit
		#@project = Project.find(params[:id])
	end

	def update
		#@project = Project.find(params[:id])
		if @project.update(project_params)
			redirect_to projects_path
		else
			render "edit"
		end
	end

	def destroy
		#@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end

	private
		def project_params
			params[:project].permit(:title)
		end

		def set_project
			@project = Project.find(params[:id])
		end
end

yoz_auth/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
      @project = Project.find(params[:project_id])
      @task = @project.tasks.create(task_params)
      redirect_to project_path(@project.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  private

      def task_params
          params[:task].permit(:title)
      end

end

yoz_auth/app/helpers/application_helper.rb
module ApplicationHelper
end

yoz_auth/app/helpers/home_helper.rb
module HomeHelper
end

yoz_auth/app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

yoz_auth/app/helpers/projects_helper.rb
module ProjectsHelper
end

yoz_auth/app/helpers/tasks_helper.rb
module TasksHelper
end

yoz_auth/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

yoz_auth/app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

yoz_auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YozSample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
  <nav>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <% if user_signed_in? %> 
      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
      <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "サインイン", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "Sign in with Github", user_omniauth_authorize_path(:twitter) %>
    <% end %>
  </nav>
</header>

	<%= image_tag "sample.png"%>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<%= yield %>
	<%= link_to "ホームに戻る", projects_path %>

</body>
</html>

yoz_auth/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<p>
	<%= f.label :タイトル %>
	<%= f.text_field :title %>
	<% if @project.errors.any? %>
	<%= @project.errors.messages[:title][0] %>
    <% end %>
</p>
<p>
	<%= f.submit %>
</p>


<% end %>

yoz_auth/app/views/projects/edit.html.erb
<h1>タスクを編集する</h1>

<%= render 'form' %>

yoz_auth/app/views/projects/index.html.erb
<h1>Projects</h1>


<ul>
	<% @projects.each do |project| %>
    <li><%= link_to project.title, project_path(project.id) %>
    	<%= link_to "タスク変更", edit_project_path(project.id) %>
    	<%= link_to "消去", project_path(project.id), method: :delete, data: {confirm: "本当に削除してもよろしいでしょうか"} %>
	</li>
	<li><%= @twitters %>
		
	</li>
    <% end %>
</ul>

<p><%= link_to "タスクを追加する", new_project_path %> </p>

yoz_auth/app/views/projects/new.html.erb
<h1>タスクを追加する</h1>

<%= render 'form' %>

yoz_auth/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<ul>
<% @project.tasks.each do |task| %>
<li>
    <%= task.title %>
    <%= link_to "[Delete]", project_task_path(task.project_id, task.id), method: :delete, data: { confirm: "are you sure?" } %>
</li>
<% end %>
<li>
    <%= form_for [@project, @project.tasks.build] do |f| %>
    <%= f.text_field :title %>
    <%= f.submit %>
    <% end %>
</li>
</ul>